Algoritmo "Calculo da Área de uma cincurferência 6-Q"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa do Santos
// Descrição   : Calculo da área de uma circunferência
// Autor(a)    : Matheus Pacco Silva
// Data atual  : 23/03/2022
Var
Area,Raio: real

Inicio
ESCREVAL ("Digite o raio da circunferência")
LEIA (Raio)

Area <- 3.14 * (Raio^2)

ESCREVAL ("A área da circunferência será de: ", Area)


Fimalgoritmo